name: app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.5+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  http_auth: ^1.0.1
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.11
  intl: ^0.17.0
  webview_flutter: ^3.0.0
  # third parts
  provider: ^6.0.0
  flutter_colorpicker: ^0.6.0
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.8
  syncfusion_flutter_charts: ^19.3.57
  syncfusion_flutter_pdfviewer: ^19.4.41-beta
  # firebase
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4
  firebase_analytics: ^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  # third parts
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icons/launcher_icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/pdf/privacy.pdf
    - assets/app_icons/