Map<String, String> strings = {
  "app_name": "Trading Simulator",
  "theme_mode": "Theme mode",
  "theme_color": "Theme color",
  "contact_us": "Contact us",
  "email_support": "ayman.w.hanna@gmail.com",
  "chat_support": "chat with us",
  "contact_us_message": "Contact us through Email or Chat",
  "light": "Light",
  "dark": "Dark",
  "tab_home": "Home",
  "tab_account": "My Account",
  "tab_settings": "Settings",
  "color_picker": "Pick a color",
  "sign_in_sub_header": "To start treading.",
  "form_email": "Email Address",
  "form_paypal_email": "Paypal Email Address",
  "form_password": "Password",
  "form_confirm_password": "Confirm Password",
  "form_name": "Name",
  "form_email_validate": "Please enter a valid email address",
  "form_password_validate": "Password must be at least 8 characters",
  "form_password_confirmed_validate": "Password not matched",
  "form_name_validate": "Name must be at least 3 characters",
  "sign_in": "Sign In",
  "sign_up": "Sign Up",
  "sign_out": "Sign Out",
  "forget_password": "Forget my password",
  "not_member": "Not a member?",
  "already_member": "Already a member?",
  "succeed": "Successful Operation.",
  "error_occurred": "An Error Occurred!",
  "unknown_error": "An error occurred, Try again later.",
  "check_internet": "Check internet connection",
  "wrong_password": "Password is incorrect",
  "already_signed_up":
      "The email address is already in use by another account.",
  "invalid_email": "That email is already has an account",
  "email_not_found": "Unregistered email",
  "too_many_attempts":
      "We have blocked all requests from this device due to unusual activity. Try again later.",
  "requires-recent-login":
      "Sign out, sign in again then try the update operation",
  "reset_password_email_sent":
      "Password reset link has been sent to your email",
  "email_verification_sent": "Check your email to confirm it then sign in.",
  "my_services": "My Services",
  "add_service": "Add Service",
  "my_profile": "My Profile",
  "account_status": "Account Status",
  "update_name": "Update name",
  "update_email": "Update email",
  "update_password": "Update password",
  "update_success": "Successful update",
  "update_failed": "Failure update",
  "wrong": "Something wrong",
  "form_service_email_validate": "Invalid email",
  "service_price": "Service Price",
  "form_service_price_validate": "Invalid service Price",
  "form_service_key_word_validate": "Key words must be at least 3 words",
  "enable": "Enable",
  "disable": "Disable",
  "edit": "Edit",
  "delete": "Delete",
  "ok": "Ok",
  "accept": "Accept",
  "cancel": "Cancel",
  "empty": "Empty message",
  "update": "Update",
  "done": "Done",
  "moved_to_in_processing": "Moved to in processing",
  "clipboard": "Copied to clipboard",
  "accept_request_confirmation": "Are you sure you want to accept this request?",
  "delete_request_confirmation": "Are you sure you want to delete this request?",
  "amount": "Amount",
  "your_selling_requests": "Your selling requests",
  "your_buying_requests": "Your buying requests",
  "convert": "Convert",
  "buy": "Buy",
  "sell": "Sell",
  "form_amount": "Amount",
  "form_price_per_coin": "Price Per Coin",
  "form_amount_validate": "Amount is invalid.",
  "form_price_per_coin_validate": "Price is invalid.",
  "withdrawal": "Withdrawal",
  "total_price": "Total price",
  "deposit": "Deposit",
  "change_password": "Change Password",
  "notifications": "Notifications",
  "my_wallet": "My Wallet",
  "privacy_policy": "Privacy policy",
  "fee_not_included": "Fees not included",
  "fees": "Fees",
  "total_cost": "Total cost",
  "usd_balance": "Your balance that can be used",
  "no_requests": "No requests yet",
  "publish": "Publish",
  "accepted_date": "Accepted date",
  "filter_requests": "Filter Requests",
  "my_requests": "My Requests",
  "all_requests": "All Requests",
  "fees_not_includes": "Fees (2%) are not included",
  "deposit_history": "Deposit history",
  "currency": "Currency",
  "price_per_coin": "Price per coin",
  "publish_date": "Publish date",
  "other_currencies_balance": "Your balance of currencies",
  "withdrawal_request": "Submit a withdrawal request",
  "previous_withdrawals": "Previous withdrawals",
  "current_withdrawal_request": "Current withdrawal request (in progress)",
  "minimum_withdrawal": "Minimum withdrawal is 10.00 \$",
  "maximum_withdrawal": "Maximum withdrawal is 1000.00 \$",
  "minimum_deposit": "Minimum deposit is 5.00 \$",
  "maximum_deposit": "Maximum deposit is 1000.00 \$",
  "insufficient_balance": "Your balance is insufficient",
  "already_requested":
      "You cannot submit a new request until the existing one has been reviewed."
          " To modify or delete the existing request, contact support",
  "no_notifications": "No notifications",
  "message_hint": "Message",
  "buying_requests": "Buying Requests",
  "buying_request": "Buying Request",
  "selling_requests": "Selling Requests",
  "selling_request": "Selling Request",
  "in_process_requests": "In Process Requests",
  "completed_requests": "Completed Requests",
  "request_deleted": "Request deleted",
  "privacy_policy_message": "By sign up, you agree to the privacy policy",
};

// sb-c43oxw10708105@personal.example.com
